-- =============================================================
--  myWebsite Database Schema
--  PostgreSQL 15+
--  Run this entire file in pgAdmin 4 Query Tool
--  (connected to the "mywebsite" database)
-- =============================================================

-- ---------------------------------------------------------------
-- 0. Extensions
-- ---------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- provides gen_random_uuid()

-- ---------------------------------------------------------------
-- 1. ROLES  (admin | user)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    id          SMALLINT     PRIMARY KEY,
    name        VARCHAR(20)  NOT NULL UNIQUE   -- 'ADMIN', 'USER'
);

INSERT INTO roles (id, name) VALUES
    (1, 'ADMIN'),
    (2, 'USER')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------
-- 2. USERS
--    - Admin account is seeded manually (no public registration).
--    - Regular users register with email + password + display info.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,          -- bcrypt hash, NEVER plain text
    username      VARCHAR(50)   NOT NULL UNIQUE,
    first_name    VARCHAR(100)  NOT NULL,
    last_name     VARCHAR(100)  NOT NULL,
    role_id       SMALLINT      NOT NULL DEFAULT 2 REFERENCES roles(id),
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Seed the admin account (password must be replaced with a real bcrypt hash
-- generated by your Spring Boot app — never store plain text).
-- Placeholder hash below = bcrypt("change_me_immediately")
INSERT INTO users (email, password_hash, username, first_name, last_name, role_id)
VALUES (
    'admin@mywebsite.com',
    '$2a$12$/0ku453/2rPKtfxun1utw.2/aO0TQe0NvYADHW0PuSEfWuMNqrBl2',
    'admin',
    'Admin',
    'User',
    1
) ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------
-- 3. POSTS  (blog entries / thoughts written by admin)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS posts (
    id           UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id    UUID          NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title        VARCHAR(255)  NOT NULL,
    slug         VARCHAR(255)  NOT NULL UNIQUE,   -- URL-friendly e.g. "my-first-post"
    summary      TEXT,                            -- short teaser shown on list pages
    body         TEXT          NOT NULL,          -- full post content (Markdown / HTML)
    cover_image  VARCHAR(500),                    -- URL to cover image (GCS bucket later)
    is_published BOOLEAN       NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------
-- 4. TAGS  (optional but very useful for filtering posts later)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
    id    SERIAL       PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id  UUID     NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id   INTEGER  NOT NULL REFERENCES tags(id)  ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- ---------------------------------------------------------------
-- 5. COMMENTS  (by registered users on posts)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS comments (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id      UUID         NOT NULL REFERENCES posts(id)  ON DELETE CASCADE,
    author_id    UUID         NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    parent_id    UUID                  REFERENCES comments(id) ON DELETE CASCADE,  -- NULL = top-level; set = reply
    body         VARCHAR(6000) NOT NULL,   -- ~1000 words @ avg 6 chars/word
    is_approved  BOOLEAN      NOT NULL DEFAULT TRUE,   -- set FALSE to moderate
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT comments_body_length CHECK (length(body) BETWEEN 1 AND 6000)
);

-- ---------------------------------------------------------------
-- 6. RESUME  (structured resume data — easier to update via API)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_sections (
    id          SERIAL        PRIMARY KEY,
    section     VARCHAR(50)   NOT NULL,   -- 'experience', 'education', 'skills', etc.
    sort_order  SMALLINT      NOT NULL DEFAULT 0,
    title       VARCHAR(255)  NOT NULL,
    subtitle    VARCHAR(255),             -- company / institution
    location    VARCHAR(255),
    start_date  DATE,
    end_date    DATE,                     -- NULL = present
    description TEXT,
    is_visible  BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------
-- 7. AUTOMATIC updated_at trigger  (fires on every UPDATE)
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['users','posts','comments','resume_sections']
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            t, t
        );
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------
-- 8. Indexes for common query patterns
-- ---------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_posts_author        ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_published     ON posts(is_published, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_slug          ON posts(slug);
CREATE INDEX IF NOT EXISTS idx_comments_post       ON comments(post_id);
CREATE INDEX IF NOT EXISTS idx_comments_author     ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent     ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_users_email         ON users(email);
CREATE INDEX IF NOT EXISTS idx_resume_section_sort ON resume_sections(section, sort_order);

